services:
  - type: web
    name: url-shortener-dsa
    env: python
    buildCommand: pip install -r requirements.txt && g++ -o url_shortener src/url_shortener.cpp
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 